controllers/KlienController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Klien;
use app\models\Login;
use app\models\search\KlienSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KlienController implements the CRUD actions for Klien model.
 */
class KlienController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
         Yii::$app->controller->enableCsrfValidation = false;
        
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

             'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','delete','update','informasi','informasi2','informasi3'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],   
        ];
    }

    /**
     * Lists all Klien models.
     * @return mixed
     */
    public function actionInformasi()
    {
       

        return $this->render('informasi');
    }
     public function actionInformasi2()
    {
       

        return $this->render('informasi2');
    }

      public function actionInformasi3()
    {
       

        return $this->render('informasi3');
    }
    
    public function actionIndex()
    {
        $searchModel = new KlienSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Klien model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
         return $this->render('view', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);

    }

     public function actionDetail($id)
    {
        return $this->render('view_detail', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);
    }


    public function actionReg($id)
    {
         $this->layout='column5';

        return $this->render('view_klien', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);
    }

    /**
     * Creates a new Klien model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
          $model = new Klien();
        
        

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $model_login = new Login();
        $model_login->username=$model->id_user;
        $model_login->password=$model->password;
        $model_login->role='user';
        $model_login->save();

               return $this->redirect(['view', 'id' => $model->id_user]);

        } else {
        $dat="admin";
        $data=Klien::find()->where(['<>','id_user',$dat])->orderBy(['id_user'=>SORT_DESC])->one();
        if(count($data)<1){
        $kode="U0001";
        }else{
        $kode= "U". substr( "00000". strval(substr($data->id_user,-4)+1),-4) ;
        }
         $model->id_user=$kode;

            return $this->render('create', [
                'model' => $model,
                'kode'=>$kode,
            ]);
        }
    }

    public function actionNew()
    {
        $this->layout='column5';
        $model = new Klien();
        
        

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $model_login = new Login();
        $model_login->username=$model->id_user;
        $model_login->password=$model->password;
        $model_login->role='user';
        $model_login->save();

               return $this->redirect(['reg', 'id' => $model->id_user]);

        } else {
        $dat="admin";
        $data=Klien::find()->where(['<>','id_user',$dat])->orderBy(['id_user'=>SORT_DESC])->one();
        if(count($data)<1){
        $kode="U0001";
        }else{
        $kode= "U". substr( "00000". strval(substr($data->id_user,-4)+1),-4) ;
        }
         $model->id_user=$kode;

            return $this->render('new', [
                'model' => $model,
                'kode'=>$kode,
            ]);
        }
    }

    /**
     * Updates an existing Klien model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model_login=Login::find()->where(['username'=>$id])->one();
        $model->password=$model_login->password;
        $model->repassword=$model_login->password;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model_login->load(Yii::$app->request->post()) && $model_login->save()) {
            return $this->redirect(['detail', 'id' => $model->id_user]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'model_login'=>$model_login,
            ]);
        }
    }

    /**
     * Deletes an existing Klien model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Login::find()->where(['username'=>$id])->one()->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Klien model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Klien the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Klien::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/LoginController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Login;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * LoginController implements the CRUD actions for Login model.
 */
class LoginController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    { 
        Yii::$app->controller->enableCsrfValidation = false;
        
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

             'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','view','delete','update'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],   
        ];


    }

    /**
     * Lists all Login models.
     * @return mixed
     */
    public function actionIndex()
    {
        yii::$app->session->set('mn',"user");

        $dataProvider = new ActiveDataProvider([
            'query' => Login::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Login model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Login model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Login();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Login model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Login model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Login model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Login the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Login::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/Rule1Controller.php
<?php

namespace app\controllers;

use Yii;
use app\models\Rule1;
use app\models\search\Rule1Search;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * Rule1Controller implements the CRUD actions for Rule1 model.
 */
class Rule1Controller extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        Yii::$app->controller->enableCsrfValidation = false;
        
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

             'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','view','delete','update'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],   
        ];
    }

    /**
     * Lists all Rule1 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new Rule1Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Rule1 model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Rule1 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Rule1();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Rule1 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Rule1 model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Rule1 model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Rule1 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Rule1::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/column1.php
 <?php echo $content; ?>

views/layouts/column2.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Sepeda" />
    <meta name="author" content="" />
    
    <title>PUGAR</title>
    
    <?php

         $this->registerCssFile('@web/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css');
         $this->registerCssFile('@web/css/font-icons/entypo/css/entypo.css');
         $this->registerCssFile('@web/css/bootstrap.css');
         $this->registerCssFile('@web/css/neon-core.css');
         $this->registerCssFile('@web/css/neon-theme.css');
         $this->registerCssFile('@web/css/neon-forms.css');
         $this->registerCssFile('@web/css/custom.css');
         $this->registerCssFile('@web/css/font-awesome.css');
         $this->registerCssFile('@web/css/skins/blue.css');
         
   ?>

<?php
$this->registerJsFile('@web/js/jquery-1.11.0.min.js');

?>
    
<?php $this->head() ?>        
</head>
<body class="page-body" data-url="http://neon.dev" style="color:#00000">
<?php $this->beginBody() ?>
<div class="page-container">
    
    <div class="sidebar-menu">
        
            
        <header class="logo-env">
            
            <!-- logo -->
            <div class="logo">
                <a href="index.html">
                    <img src="<?= Yii::$app->request->baseUrl ?>/images/logo2.png" width="120" alt="" />
                </a>
            </div>
            
                        <!-- logo collapse icon -->
                        
            <div class="sidebar-collapse">
                <a href="#" class="sidebar-collapse-icon with-animation">

                    <i class="entypo-menu"></i>
                </a>
            </div>
            
                                    
            
            
            <div class="sidebar-mobile-menu visible-xs">
                <a href="#" class="with-animation">
                    <i class="entypo-menu"></i>
                </a>
            </div>
            
        </header>
     
                <div class="sidebar-user-info">
            
            <div class="sui-normal">
                <a href="#" class="user-link">
                    <img src="<?= Yii::$app->request->baseUrl ?>/images/thumb-1a.png" alt="" class="img-circle" />
                    
                    <span>Welcome,</span>
                    <strong><?=  Yii::$app->user->identity->username; ?></strong>
                </a>
            </div>
            
            <div class="sui-hover inline-links animate-in"><!-- You can remove "inline-links" class to make links appear vertically, class "animate-in" will make A elements animateable when click on user profile -->             
               <a href="<?= Url::to(['klien/detail','id'=>Yii::$app->user->identity->username]); ?>">
                    <i class="fa fa-user-circle"></i>
                    <span> Detail User</span>
                </a>
                
               <a href="<?= Url::to(['konsultasi/mulai']); ?>">
                    <i class="fa fa-file-zip-o"></i>
                    <span> Proses</span>
                </a>
                
                <a href="<?= Url::to(['site/logout'])?>">
                    <i class="entypo-lock"></i>
                    Log Out
                </a>
                
                <span class="close-sui-popup">&times;</span><!-- this is mandatory -->          </div>
        </div>           
        
        
                
        
                
        <ul id="main-menu" class="">
<li>
                <a href="<?= Url::to(['konsultasi/home']); ?>">
                    <i class="fa fa-home"></i>
                    <span> Home</span>
                </a>
         
            </li>
            <li>
                        <a href="#">
                          <i class="fa fa-address-book-o "></i>
                            <span>Informasi</span>
                        </a>
                        <ul>
                            <li>
                                <a href="<?= Url::to(['klien/informasi']); ?>">
                                <i class="fa fa-address-card"></i>
                                    <span>Tentang pakar</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?= Url::to(['klien/informasi3']); ?>">
                                <i class="fa fa-newspaper-o"></i>
                                    <span>Jenis-jenis garam</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?= Url::to(['klien/informasi2']); ?>">
                                     <i class="fa fa-address-card-o"></i>
                                    <span>Pembuat web</span>
                                </a>
                            </li>
                        </ul>
                    </li>
<?php 
if(Yii::$app->user->identity->role=="user"){


?>
             <li>
                <a href="<?= Url::to(['konsultasi/detail']); ?>">
                    <i class="fa fa-medkit"></i>
                    <span> Riwayat konsultasi user</span>
                </a>
         
            </li>
<?php
}else{



?>
            <li>
                <a href="<?= Url::to(['klien/index']); ?>">
                    <i class="fa fa-users"></i>
                    <span> Klien</span>
                </a>
         
            </li>
            <li>
                <a href="<?= Url::to(['konsultasi/index']); ?>">
                    <i class="fa fa-medkit"></i>
                    <span> Riwayat konsultasi</span>
                </a>
         
            </li>
            


                <li>
                <a href="<?= Url::to(['rule1/index']); ?>">
                    <i class="fa fa-history"></i>
                    <span> Rule </span>
                </a>
         
            </li>
 <?php
 }
 ?>           
            <li>
                <a href="<?= Url::to(['konsultasi/mulai']); ?>">
                    <i class="fa fa-file-zip-o"></i>
                    <span> Proses</span>
                </a>
         
            </li>
          
           

             <li>
                <a href="<?= Url::to(['klien/detail','id'=>Yii::$app->user->identity->username]); ?>">
                    <i class="fa fa-user-circle"></i>
                    <span> Detail User</span>
                </a>
            </li>

            <li>
            <a href="<?= Url::to(['site/logout'])?>">
                    <i class="entypo-lock"></i>
                    Log Out
            </a>
            </li>

         </ul>
                
    </div>  
    <div class="main-content">
        
<div class="row">
    
    <!-- Profile Info and Notifications -->
    <div class="col-md-6 col-sm-8 clearfix">
        
     <!--   APLIKASI KONSULTASI GARAM-->
<h1><strong>
                    <i class="fa fa-medkit"></i>
                    <span style="color:#18217A">PUGAR</span>
                    <p><i class="fa fa-map-pin"></i>   Desa Sedayulawas, Kecamatan Brondong, Kebupaten Lamongan</p>
</strong></h1>      
                
        
    
    </div>
    
    
    <!-- Raw Links -->
    <div class="col-md-6 col-sm-4 clearfix hidden-xs">
        
        <ul class="list-inline links-list pull-right">
            
            
            
            <li class="sep"></li>
            
                        
          
            
            <li class="sep"></li>
            
            <li>
                <a  href="<?= Url::to(['site/logout'])?>" data-method="post">
                    Log Out <i class="entypo-logout right"></i>
                </a>
            </li>
        </ul>
        
    </div>
    
</div>

<hr />
     
<div class="row">
    <div class="col-md-12">
     <!-- ini isi utama  -->
     <?php echo $content; ?>
    
    </div>
</div>


<!-- Footer -->
</div>
    
</div>
    <?php
            $this->registerJsFile('@web/js/gsap/main-gsap.js');
            $this->registerJsFile('@web/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js');
            $this->registerJsFile('@web/js/bootstrap.js');
            $this->registerJsFile('@web/js/joinable.js');
            $this->registerJsFile('@web/js/resizeable.js');
            $this->registerJsFile('@web/js/neon-api.js');
            $this->registerJsFile('@web/js/bootstrap-switch.min.js');
            $this->registerJsFile('@web/js/neon-chat.js');
            $this->registerJsFile('@web/js/neon-custom.js');
            $this->registerJsFile('@web/js/neon-demo.js');
?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>    

views/layouts/column3.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;


?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Neon Admin Panel" />
  <meta name="author" content="" />
  
  <title>PUGAR</title>
  
    <?php

         $this->registerCssFile('@web/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css');
         $this->registerCssFile('@web/css/font-icons/entypo/css/entypo.css');
         $this->registerCssFile('@web/css/bootstrap.css');
         $this->registerCssFile('@web/css/neon-core.css');
         $this->registerCssFile('@web/css/neon-theme.css');
         $this->registerCssFile('@web/css/neon-forms.css');
         $this->registerCssFile('@web/css/custom.css');
         $this->registerCssFile('@web/css/font-awesome.css');
         $this->registerCssFile('@web/css/skins/blue.css');
   ?>

<?php
$this->registerJsFile('@web/js/jquery-1.11.0.min.js');

?>

  <!--[if lt IE 9]><script src="assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
<?php $this->head() ?>        

</head>
<body class="page-body login-page" data-url="http://neon.dev">
<?php $this->beginBody() ?>
<div class="login-container">
  
  
  <div class="login-progressbar">
    <div></div>
  </div>
  
  <div class="login-form">
    
    <div class="login-content">
      
     
     <br>
       <?php echo $content; ?>
      
      
      <div class="login-bottom-links">
        
        
        
        <br />
        
        
        
      </div>
      
    </div>
    
  </div>
  
</div>
<?php
            $this->registerJsFile('@web/js/gsap/main-gsap.js');
            $this->registerJsFile('@web/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js');
            $this->registerJsFile('@web/js/bootstrap.js');
            $this->registerJsFile('@web/js/joinable.js');
            $this->registerJsFile('@web/js/resizeable.js');
            $this->registerJsFile('@web/js/neon-api.js');
            $this->registerJsFile('@web/js/bootstrap-switch.min.js');
            $this->registerJsFile('@web/js/neon-chat.js');
            $this->registerJsFile('@web/js/neon-custom.js');
            $this->registerJsFile('@web/js/neon-demo.js');
if (class_exists('yii\debug\Module')) {
    $this->off(\yii\web\View::EVENT_END_BODY, [\yii\debug\Module::getInstance(), 'renderToolbar']);
}
?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>    

views/layouts/column4.php
<?php


use yii\helpers\Html;
use yii\helpers\Url;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lumino - Forms</title>
<?php

         $this->registerCssFile('@web/css/bootstrap.min.css');
         $this->registerCssFile('@web/fonts/css/font-awesome.min.css');
         $this->registerCssFile('@web/css/datepicker3.css');
         $this->registerCssFile('@web/css/styles.css');
         
                 
        ?>


<!--Icons-->
<?php
$this->registerJsFile('@web/js/lumino.glyphs.js');

?>


<style>
#<?= yii::$app->session->get('mn'); ?>{
     background-color:#e0eeee!important;
}
</style>
<?php $this->head() ?>    
</head>

<body>
<?php $this->beginBody() ?>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span></span>Admin</a>
                <ul class="user-menu">
                    <li class="dropdown pull-right">
                        <a <a href="<?= Url::to(['site/logout'])?>" data-method="post"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> Logout User</a>
                       
                    </li>
                </ul>
            </div>
                            
        </div><!-- /.container-fluid -->
    </nav>
        
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li id="siswa"><a href="<?= Url::to(['siswa/index']); ?>">
            <svg class="glyph stroked male user ">
            <use xlink:href="#stroked-male-user"/></svg>
            Data Siswa
            </a></li>

            <li id="bobot"><a href="<?= Url::to(['bobot/index']); ?>">
            <svg class="glyph stroked clipboard with paper">
            <use xlink:href="#stroked-clipboard-with-paper"/></svg>
            Bobot
            </a></li>


            <li id="proses"><a href="<?= Url::to(['penilaian-proses/index']); ?>">
            <svg class="glyph stroked dashboard dial">
            <use xlink:href="#stroked-dashboard-dial"/></svg>
            Proses
            </a></li>
           
 
            <li role="presentation" class="divider"></li>
            <li id="user"><a href="<?= Url::to(['login/index']); ?>">
            <svg class="glyph stroked male-user">
            <use xlink:href="#stroked-male-user"></use></svg> 
            User Login
            </a></li>
        </ul>

    </div><!--/.sidebar-->
        
    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">           
      
    
                
        
        <div class="row">

          <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            
                                    <?php echo $content; ?>
        
          </div><!-- /.col -->
        </div><!-- /.row -->
        
    </div><!--/.main-->
<?php
            $this->registerJsFile('@web/js/jquery-1.11.1.min.js');
            $this->registerJsFile('@web/js/bootstrap.min.js');
            $this->registerJsFile('@web/js/chart.min.js');
            $this->registerJsFile('@web/js/chart-data.js');
            $this->registerJsFile('@web/js/easypiechart.js');
            $this->registerJsFile('@web/js/easypiechart-data.js');
            $this->registerJsFile('@web/js/bootstrap-datepicker.js');
            $this->registerJsFile('@web/js/custom.js');


?>

    <script>
        !function ($) {
            $(document).on("click","ul.nav li.parent > a > span.icon", function(){        
                $(this).find('em:first').toggleClass("glyphicon-minus");      
            }); 
            $(".sidebar span.icon").find('em:first').addClass("glyphicon-plus");
        }(window.jQuery);

        $(window).on('resize', function () {
          if ($(window).width() > 768) $('#sidebar-collapse').collapse('show')
        })
        $(window).on('resize', function () {
          if ($(window).width() <= 767) $('#sidebar-collapse').collapse('hide')
        })
    </script>   
<?php $this->endBody() ?>    
</body>

</html>
<?php $this->endPage() ?>