controllers/KlienController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Klien;
use app\models\Login;
use app\models\search\KlienSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * KlienController implements the CRUD actions for Klien model.
 */
class KlienController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
         Yii::$app->controller->enableCsrfValidation = false;
        
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],

             'access' => [
                        'class' => \yii\filters\AccessControl::className(),
                        'only' => ['index','create','delete','update','informasi','informasi2','informasi3'],
                        'rules' => [
                            // allow authenticated users
                            [
                                'allow' => true,
                                'roles' => ['@'],
                            ],
                            // everything else is denied
                        ],
                    ],   
        ];
    }

    /**
     * Lists all Klien models.
     * @return mixed
     */
    public function actionInformasi()
    {
       

        return $this->render('informasi');
    }
     public function actionInformasi2()
    {
       

        return $this->render('informasi2');
    }

      public function actionInformasi3()
    {
       

        return $this->render('informasi3');
    }
    
    public function actionIndex()
    {
        $searchModel = new KlienSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Klien model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
         return $this->render('view', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);

    }

     public function actionDetail($id)
    {
        return $this->render('view_detail', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);
    }


    public function actionReg($id)
    {
         $this->layout='column5';

        return $this->render('view_klien', [
            'model' => $this->findModel($id),
            'model_login'=>Login::find()->where(['username'=>$id])->one(),
        ]);
    }

    /**
     * Creates a new Klien model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
          $model = new Klien();
        
        

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $model_login = new Login();
        $model_login->username=$model->id_user;
        $model_login->password=$model->password;
        $model_login->role='user';
        $model_login->save();

               return $this->redirect(['view', 'id' => $model->id_user]);

        } else {
        $dat="admin";
        $data=Klien::find()->where(['<>','id_user',$dat])->orderBy(['id_user'=>SORT_DESC])->one();
        if(count($data)<1){
        $kode="U0001";
        }else{
        $kode= "U". substr( "00000". strval(substr($data->id_user,-4)+1),-4) ;
        }
         $model->id_user=$kode;

            return $this->render('create', [
                'model' => $model,
                'kode'=>$kode,
            ]);
        }
    }

    public function actionNew()
    {
        $this->layout='column5';
        $model = new Klien();
        
        

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $model_login = new Login();
        $model_login->username=$model->id_user;
        $model_login->password=$model->password;
        $model_login->role='user';
        $model_login->save();

               return $this->redirect(['reg', 'id' => $model->id_user]);

        } else {
        $dat="admin";
        $data=Klien::find()->where(['<>','id_user',$dat])->orderBy(['id_user'=>SORT_DESC])->one();
        if(count($data)<1){
        $kode="U0001";
        }else{
        $kode= "U". substr( "00000". strval(substr($data->id_user,-4)+1),-4) ;
        }
         $model->id_user=$kode;

            return $this->render('new', [
                'model' => $model,
                'kode'=>$kode,
            ]);
        }
    }

    /**
     * Updates an existing Klien model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model_login=Login::find()->where(['username'=>$id])->one();
        $model->password=$model_login->password;
        $model->repassword=$model_login->password;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            if ($model_login->load(Yii::$app->request->post()) && $model_login->save()) {
            return $this->redirect(['detail', 'id' => $model->id_user]);
            }
        } else {
            return $this->render('update', [
                'model' => $model,
                'model_login'=>$model_login,
            ]);
        }
    }

    /**
     * Deletes an existing Klien model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Login::find()->where(['username'=>$id])->one()->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Klien model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Klien the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Klien::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
        public $layout='column3';

    public function behaviors()
    {
        Yii::$app->controller->enableCsrfValidation = false;

        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                   // 'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('home');
    }

    public function actionLogin()
    {


        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<div class="container">
        		<div class="row">
        			<div class="col-md-12">
        				
        				<div class="row">
        					
        					<div class="col-md-12 col-sm-12 col-xs-12 main-content">
                                

								<div class="row">
									<div class="col-md-6 col-sm-6 col-xs-12">
                                        <header class="content-title">
                                            <h2 class="title">Welcome to Venedor</h2>
                                        </header>
										<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Venedor is a fully responsive Magento theme with advanced admin module. Based on Bootstrap’s 12 column 1200px responsive grid Theme. Great looks on desktops, tablets and mobiles. <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Venedor is extremely customizable, easy to use and fully responsive. Suitable for every type of store. Great as a starting point for your custom projects. This theme includes several extensions including ajax price slider that will help you improve your sales. We supply a full help with our products and after purchase support to all our customers. <a href="#">Buy Venedor Theme!</a></p>
									</div><!-- End .col-md-6 -->
									<div class="col-md-6 col-sm-6 col-xs-12">
                                        <div class="sm-margin visible-xs"></div><!-- space -->
										<img src="images/showcase.png" alt="Showcase Venedor" class="img-responsive">
									</div><!-- End .col-md-5 -->
								</div><!-- End .row -->

        						<div class="xlg-margin"></div><!-- Space -->
        						
        					

                            </div><!-- End .col-md-12 -->
                        </div><!-- End .row -->
	
        			</div><!-- End .col-md-12 -->
        		</div><!-- End .row -->
			</div><!-- End .container -->

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/home.php
                                <article class="article">
                                    <div class="article-meta-date">
                                        <span>15</span>
                                        Aug
                                    </div><!-- End .article-meta-date -->
                                    
                                    <figure class="article-media-container">
                                        <img src="images/blog/post2-large.jpg" alt="blog post">
                                    </figure>
                                    
                                    <h2><a href="single.html">Etiam laoreet sem eget eros rhoncus.</a></h2>
                                    
                                    <div class="article-meta-container clearfix">
                                        <div class="article-meta-more">
                                            <a href="#"><span class="separator"><i class="fa fa-user"></i></span>By  Admin</a>
                                            <a href="#"><span class="separator"><i class="fa fa-comments "></i></span>3 Comments</a>
                                            <a href="#"><span class="separator"><i class="fa fa-tag"></i></span>Category</a>
                                        </div><!-- End. pull-left -->
                                        
                                        <div class="article-meta-view">
                                            <a href="#"><span class="separator"><i class="fa fa-eye "></i></span>151</a>
                                            <a href="#"><span class="separator"><i class="fa fa-heart"></i></span>87</a>
                                        </div><!-- End. pull-right -->
                                    </div><!-- End .article-meta-container -->
                                    
                                    <div class="article-content-container">
                                        <p>Quisque elementum nibh at dolor pellentesque, a eleifend libero pharetra. Mauris neque felis, volutpat nec ullamcorper eget, sagittis vel enim. Nam sit amet ante egestas, gravida tellus vitae, semper eros. Nullam mattis mi at metus egestas, in porttitor lectus sodales <a href="#">Read More... </a></p>
                                    </div><!-- End .article-content-container -->
                                </article><!-- End .article -->
                                
                            <div class="pagination-container clearfix">
                                    <div class="pull-left page-count">
                                        Page 1 of 5
                                    </div><!-- End .pull-left -->
                                    
                                    <div class="pull-right">
                                        <ul class="pagination">
                                        <li class="active"><a href="#">1</a></li>
                                        <li><a href="#">2</a></li>
                                        <li><a href="#">3</a></li>
                                        <li><a href="#">4</a></li>
                                        <li><a href="#">5</a></li>
                                        <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                                        </ul>
                                    </div><!-- End .pull-right -->
                                </div><!-- End pagination-container -->

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>

        
<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

<h1 style="color:#858a91">WELCOME</h1>

        <div class="form-group">
          
          <div class="input-group">
            <div class="input-group-addon">
              <i class="entypo-user"></i>
            </div>
            <?=$form->field($model, 'username')->textInput(['autofocus' => true])->input('username', ['placeholder' => "username"])->label(false)->error(false); ?>

            

          </div>
          
        </div>
        
        <div class="form-group">
          
          <div class="input-group">
            <div class="input-group-addon">
              <i class="entypo-key"></i>
            </div>
            
<?= $form->field($model, 'password')->passwordInput()->input('password', ['placeholder' => "password"])->label(false)->error(false); ?>
          </div>
        
        </div>
        
        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block btn-login">
            <i class="entypo-login"></i>
            Login In
          </button>
        </div>
        <div class="form-group">
          <em>- or -</em>
        </div>
         
         <div class="form-group">
         <a href="<?= Url::to(['klien/new']); ?>">
          <button type="button" class="btn btn-primary btn-block btn-login">
            <i class="entypo-login"></i>
            Create account
          </button>
         </a> 
        </div>
        
        

        <!-- Implemented in v1.1.4 -->        <div class="form-group">
          <em style="color:red"><?= Html::error($model, 'password'); ?></em>
                              <div>
                                <i class="fa fa-home fa-4x" style="font-size: 26px;"></i>

                                
                              </div>

        </div>
        
      
      <?php ActiveForm::end(); ?><!-- form -->